//Common
export const SET_LOADER = "SET_LOADER";
export const SET_RESET_PASSWORD_DATA = "SET_RESET_PASSWORD_DATA";

//Authentication
export const SET_INVITED_USER_DATA = "SET_INVITED_USER_DATA";

//Educator
export const SET_ADMIN_DASHBOARD_STEP_COUNT = "SET_ADMIN_DASHBOARD_STEP_COUNT";
export const SET_INSIGHT_DASHBOARD_STEP_COUNT =
  "SET_INSIGHT_DASHBOARD_STEP_COUNT";
export const SET_EDUCATOR_DATA = "SET_EDUCATOR_DATA";
export const SET_INSIGHT_DATE_RANGE_DATA = "SET_INSIGHT_DATE_RANGE_DATA";
export const MULTIPLE_SELECTED_CLASS = "MULTIPLE_SELECTED_CLASS";
export const SET_SWITCH_SCHOOL_DATA = "SET_SWITCH_SCHOOL_DATA";
export const SET_SWITCH_SCHOOL_TIME_STAMP = "SET_SWITCH_SCHOOL_TIME_STAMP";
export const DO_SET_TIME_LINE_TAG = "DO_SET_TIME_LINE_TAG";

//Insight Dashboard Data
export const SET_INSIGHT_ADMIN_DATA = "SET_INSIGHT_ADMIN_DATA";
export const SET_MOODBYDAY_DATA = "SET_MOODBYDAY_DATA";
export const SET_STUDENT_ALL_DATA = "SET_STUDENT_ALL_DATA";
export const SET_ASK_STUDENT_ALL_DATA = "SET_ASK_STUDENT_ALL_DATA";
export const SET_INDIVIDUAL_STUDENT_DATA = "SET_INDIVIDUAL_STUDENT_DATA";
export const SET_ALL_LOGS_DATA = "SET_ALL_LOGS_DATA";
export const SET_FLAGGED_LOGS_DATA = "SET_FLAGGED_LOGS_DATA";
export const SET_POPULAR_TOPICS_DATA = "SET_POPULAR_TOPICS_DATA";
export const SET_SELECTED_STUDENT_DATA = "SET_SELECTED_STUDENT_DATA";
export const SET_STUDENT_WEBLIST_LINK_DATA = "SET_STUDENT_WEBLIST_LINK_DATA";
export const SET_ASKSTUDENT_WEBLIST_LINK_DATA = "SET_ASKSTUDENT_WEBLIST_LINK_DATA";

//Class
export const SET_CLASS_DATA = "SET_CLASS_DATA";
export const SET_CLASS_DETAIL_DATA = "SET_CLASS_DETAIL_DATA";
export const SET_STUDENT_DETAIL_DATA = "SET_STUDENT_DETAIL_DATA";
export const SET_CLASS_LIST = "SET_CLASS_LIST";
export const SET_ADD_STUDENT_DATA = "SET_ADD_STUDENT_DATA";

//Student
export const SET_STUDENT_MOOD_DETAIL_COUNT = "SET_STUDENT_MOOD_DETAIL_COUNT";
export const SET_STUDENT_CLASS_DATA = "SET_STUDENT_CLASS_DATA";
export const SET_STUDENT_JOURNAL_DATA = "SET_STUDENT_JOURNAL_DATA";
export const SET_STUDENT_JOURNAL_RESPONSE_DATA = "SET_STUDENT_JOURNAL_RESPONSE_DATA";
export const SET_MOOD_LIST_DATA = "SET_MOOD_LIST_DATA";
export const SET_BOT_RESPONSE_DATA = "SET_BOT_RESPONSE_DATA";
export const SET_MOOD_DESCRIPTION_DATA = "SET_MOOD_DESCRIPTION_DATA";
export const SET_EDIT_MOOD_ENABLE_DATA = "SET_EDIT_MOOD_ENABLE_DATA";
export const SET_STUDENT_SELECTED_CLASS = "SET_STUDENT_SELECTED_CLASS";
export const SET_STUDENT_DATA = "SET_STUDENT_DATA";
export const SET_LATEST_MOOD_DATA = "SET_LATEST_MOOD_DATA";

export const GET_NOTIFICATION_LISTING = "GET_NOTIFICATION_LISTING";
export const REMOVE_DEMO_CLASS = "REMOVE_DEMO_CLASS";
export const IS_SHOW_NOTIFICATION_BANNER = "IS_SHOW_NOTIFICATION_BANNER";
export const SELECTED_CLASS_ID="SELECTED_CLASS_ID"
export const SET_CLASS_LIST_ADMIN = 'SET_CLASS_LIST_ADMIN';

export const SET_REMOVE_SELECTED_NAME = 'SET_REMOVE_SELECTED_NAME';