import images from '../resources/images';

const dashboardCarouselData = [
  {
    id: 1,
    title: 'Cras ultricies ligula sed',
    image: images.Category1,
    rating: 4.0,
    keywords: ['Sust. Category', 'Keyword'],
    sust_category_keyword: ['Sust. Category 1', 'Sust. Category 2'],
    shop_keyword: ['Keyword 1', 'Keyword 2'],
    distance: 1,
    walk_time: 30,
    cycle_time: 10,
  },
  {
    id: 2,
    title: 'Cras ultricies ligula sed',
    image: images.Category2,
    rating: 4.3,
    keywords: ['Sust. Category', 'Keyword'],
    sust_category_keyword: ['Sust. Category 1', 'Sust. Category 2'],
    shop_keyword: ['Keyword 1', 'Keyword 2'],
    distance: 1.2,
    walk_time: 37,
    cycle_time: 14,
  },
  {
    id: 3,
    title: 'Cras ultricies ligula sed',
    image: images.Category3,
    rating: 4.7,
    keywords: ['Sust. Category', 'Keyword'],
    sust_category_keyword: ['Sust. Category 1', 'Sust. Category 2'],
    shop_keyword: ['Keyword 1', 'Keyword 2'],
    distance: 0.7,
    walk_time: 25,
    cycle_time: 8,
  },
  {
    id: 4,
    title: 'Cras ultricies ligula sed',
    image: images.Category4,
    rating: 4.0,
    keywords: ['Sust. Category', 'Keyword'],
    sust_category_keyword: ['Sust. Category 1', 'Sust. Category 2'],
    shop_keyword: ['Keyword 1', 'Keyword 2'],
    distance: 0.9,
    walk_time: 28,
    cycle_time: 8,
  },
  {
    id: 5,
    title: 'Cras ultricies ligula sed',
    image: images.Category2,
    rating: 4.6,
    keywords: ['Sust. Category', 'Keyword'],
    sust_category_keyword: ['Sust. Category 1', 'Sust. Category 2'],
    shop_keyword: ['Keyword 1', 'Keyword 2'],
    distance: 1.4,
    walk_time: 40,
    cycle_time: 18,
  },
];

export default dashboardCarouselData;
