const getProfileDetails = {
  messages: '',
  data: {
    user: {
      id: 321,
      isAdmin: 0,
      first_name: 'Jignesh',
      last_name: ' Chauhan',
      email: 'jignesh.citrusbug@gmail.com',
      email_verified_at: '2019-08-22 22:01:40',
      phone: '963852741',
      profile_photo: '',
      location_id: '',
      birthday: '',
      omise_id: 'cus_H4ROGzeMhrSIJX',
      omise_last_four: '',
      default_language: 'en',
      created_at: '2019-08-22 13:58:19',
      updated_at: '2021-02-01 21:13:53',
      deleted_at: '',
      facebook_id: '',
      follow_setting: 'Yes',
      prefecture_id: '',
      donation_credits: 0,
      share_address: 'No',
      address_address1: '',
      received_points: 0,
      pending_points: 0,
      auto_donate_npo: '3',
      bank_name: '',
      bank_branch: '',
      bank_account: '',
      bank_accountname: '',
      bank_accounttype: '',
      secondary_email: 'jignesh.citrusbug@gmail.com',
      line_id: '',
      is_staff: 'No',
      referral: '',
      full_name: 'Jignesh  Chauhan',
      subscribe_enable: 'Yes',
      api_access_token:
        't3tI0qaQ9VHWyPGg0Ftewu0wfoy3b9LJi5YHlbwiIhU8end8BJ9B5R2qxEjr',
      api_token: 'jBT07hKdqODsswjh1IUR7sIxpvY4XHWMqauq8frIw8hydXR5BjODE3A3P2cW',
      user_type: 'other',
      is_company_employee: 0,
      tax_received_preference: 1,
      tax_last_name: '',
      tax_first_name: '',
      tax_postal_code: '',
      tax_prefecture: '',
      tax_address_1: '',
      tax_address_2: '',
      tax_address_3: '',
      apple_id: '',
      introduction: 'Hie.. This is jignesh here .... !!!',
      is_ambassador: 0,
      gender: 'Male',
      is_owner: 1,
      image_url:
        'https://staging.gochiso.jp/storage/users/321/aKFU6FElLdHTXFlRTjBoiyPd9mWG4dtfUEPlaIG0.jpeg',
      userdetail: {
        id: 34,
        user_id: 321,
        timezone: '',
        latitude: '23.0742866',
        longitude: '72.5300681',
        device_type: 'android',
        device_token:
          'dcQc3oeyQpeVUiqhOejigI:APA91bEDypmORatksKK43aEZFoVkEI7SXD1DwkRsYKUMVP0H0T0cZhTtAE8SSdtE8wdLeFB0Hppm6nsBu_Bn62RRhddTJPCRjeNaNZ0Mp5o8Q8MUV9xkm7sgoBHDqIlMU7E9yYHZVnBO',
        gender: 'Male',
        line_image: '',
        fb_image: '',
        created_at: '2019-08-22 13:58:19',
        updated_at: '2021-06-09 17:16:18',
      },
    },
    statistics: {
      total_dontation_amount: '￥4263',
      supported_npo: 5,
      visited_restaurant: 4,
    },
    impacts: {
      current_page: 1,
      data: [
        {
          npo_id: 3,
          dontion_id: 2332,
          npo_cover_image:
            'https://staging.gochiso.jp/storage/npos/3/jqdyrrA3lkETIh7VuILoyXpbDF3BcNDimpO0k59T.png',
          npo_cover_image_thumb:
            'https://staging.gochiso.jp/storage/npos/3/jqdyrrA3lkETIh7VuILoyXpbDF3BcNDimpO0k59T.png',
          npo_name: 'ACCESS',
          impact_msg: '￥328',
        },
        {
          npo_id: 16,
          dontion_id: 1762,
          npo_cover_image:
            'https://staging.gochiso.jp/storage/npos/16/vSRqVSzUk5CGdEXh9qmIfIIThazTJufeQ3lite3j.jpeg',
          npo_cover_image_thumb:
            'https://staging.gochiso.jp/storage/npos/16/vSRqVSzUk5CGdEXh9qmIfIIThazTJufeQ3lite3j.jpeg',
          npo_name: 'NPO After School',
          impact_msg: '￥3545',
        },
        {
          npo_id: 23,
          dontion_id: 1116,
          npo_cover_image:
            'https://staging.gochiso.jp/storage/npos/23/38b053d0a6a3cb2e298fe0a9df663160.jpeg',
          npo_cover_image_thumb:
            'https://staging.gochiso.jp/storage/npos/23/38b053d0a6a3cb2e298fe0a9df663160.jpeg',
          npo_name: 'TELL',
          impact_msg: '￥60',
        },
        {
          npo_id: 27,
          dontion_id: 1113,
          npo_cover_image:
            'https://staging.gochiso.jp/storage/npos/27/mHzXPwZEuAPR5gxFJ4TyZa475ktOvKux9XFcDVyA.jpeg',
          npo_cover_image_thumb:
            'https://staging.gochiso.jp/storage/npos/27/mHzXPwZEuAPR5gxFJ4TyZa475ktOvKux9XFcDVyA.jpeg',
          npo_name: 'Family & Friends Project',
          impact_msg: '￥90',
        },
        {
          npo_id: 44,
          dontion_id: 1102,
          npo_cover_image:
            'https://staging.gochiso.jp/storage/npos/44/nRaAStPAdz9pSybrZwX32uVz6xRl76H8iUIAQrln.jpeg',
          npo_cover_image_thumb:
            'https://staging.gochiso.jp/storage/npos/44/nRaAStPAdz9pSybrZwX32uVz6xRl76H8iUIAQrln.jpeg',
          npo_name: 'Hope International Development Agency Japan ',
          impact_msg: '￥60',
        },
      ],
      from: 1,
      last_page: 1,
      next_page_url: '',
      path: 'https://staging.gochiso.jp/api/v2.0/get-profile',
      per_page: 9,
      prev_page_url: '',
      to: 5,
      total: 5,
    },
  },
  status: 'true',
  code: 200,
};

export default getProfileDetails;
